const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let stores=JSON.parse(localStorage.pp_stores||'null')||[{id:'1',name:'Магазин 1',target:22},{id:'2',name:'Магазин 2',target:18},{id:'3',name:'Магазин 3',target:25}];
let hist=JSON.parse(localStorage.pp_history||'[]'),edit=null;
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function save(){localStorage.pp_stores=JSON.stringify(stores);localStorage.pp_history=JSON.stringify(hist)}
function calc(){let s=stores.find(x=>x.id==$('#store').value)||stores[0],q=+$('#qty').value||0,p=+$('#pct').value||0,t=s?.target||0,plan=p?Math.round(q/(p/100)*(t/100)):0,need=Math.max(0,plan-q),done=plan?q/plan:0;$('#target').textContent=t+'%';$('#plan').textContent=plan||'—';$('#missing').textContent=plan?need:'—';$('#now').textContent=q;$('#need').textContent=plan?need:'—';$('#done').textContent=plan?Math.round(done*100)+'%':'—';$('#bar').style.width=Math.min(100,done*100)+'%';return{s,q,p,t,plan,need,done}}
function render(){let old=$('#store').value;$('#store').innerHTML=stores.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');if(stores.some(s=>s.id==old))$('#store').value=old;$('#storeList').innerHTML=stores.map(s=>`<div class="item"><div><b>${esc(s.name)}</b><div class="sub">Плановая доля: ${s.target}%</div></div><div class="actions2"><button class="small" data-e="${s.id}">Изм.</button><button class="small" data-d="${s.id}">Удал.</button></div></div>`).join('');$$('[data-e]').forEach(b=>b.onclick=()=>open(b.dataset.e));$$('[data-d]').forEach(b=>b.onclick=()=>{if(stores.length<2)return alert('Нельзя удалить последний магазин');if(confirm('Удалить магазин?')){stores=stores.filter(s=>s.id!=b.dataset.d);save();render()}});calc()}
function renderHistory(){$('#historyList').innerHTML=hist.length?hist.slice().reverse().map(h=>`<div class="item"><div><b>${esc(h.name)}</b><div class="sub">${h.date}</div></div><div style="text-align:right"><b>${h.q}/${h.plan} шт.</b><div class="sub">${h.done}% · не хватает ${h.need}</div></div></div>`).join(''):'<div class="card"><span style="color:#667085">История пока пустая.</span></div>'}
function stats(){$('#checks').textContent=hist.length;if(!hist.length){$('#average').textContent='—';$('#totalNow').textContent='0';$('#totalNeed').textContent='0';$('#byStores').innerHTML='';return}let avg=hist.reduce((a,x)=>a+x.done,0)/hist.length;$('#average').textContent=Math.round(avg)+'%';$('#totalNow').textContent=hist.reduce((a,x)=>a+x.q,0);$('#totalNeed').textContent=hist.reduce((a,x)=>a+x.need,0);let m={};hist.forEach(x=>(m[x.id]??=[]).push(x));$('#byStores').innerHTML=Object.values(m).map(a=>{let x=a[a.length-1],v=a.reduce((s,y)=>s+y.done,0)/a.length;return`<div class="storeline"><b>${esc(x.name)}</b><b>${Math.round(v)}%</b></div>`}).join('')}
function open(id){edit=id||null;let s=stores.find(x=>x.id==id);$('#mtitle').textContent=s?'Изменить магазин':'Новый магазин';$('#mname').value=s?.name||'';$('#mtarget').value=s?.target||22;$('#modal').classList.remove('hidden')}
function close(){$('#modal').classList.add('hidden')}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.id).classList.add('active');renderHistory();stats()});
$('#store').onchange=calc;$('#qty').oninput=calc;$('#pct').oninput=calc;
$('#save').onclick=()=>{let x=calc();if(!x.p||!x.plan)return alert('Введи текущую долю из приложения.');hist.push({id:x.s.id,name:x.s.name,q:x.q,p:x.p,target:x.t,plan:x.plan,need:x.need,done:Math.round(x.done*100),date:new Date().toLocaleString('ru-RU')});save();renderHistory();stats();alert('Проверка сохранена')};
$('#add').onclick=()=>open();$('#close').onclick=close;$('#cancel').onclick=close;
$('#msave').onclick=()=>{let n=$('#mname').value.trim(),t=+$('#mtarget').value;if(!n||t<=0)return alert('Заполни название и процент');if(edit){let s=stores.find(x=>x.id==edit);s.name=n;s.target=t}else stores.push({id:Date.now().toString(),name:n,target:t});save();render();close()};
$('#clear').onclick=()=>{if(confirm('Очистить историю?')){hist=[];save();renderHistory();stats()}};
$('#help').onclick=()=>$('#helpbox').classList.remove('hidden');$('#ok').onclick=()=>$('#helpbox').classList.add('hidden');
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
render();renderHistory();stats();calc();